services:
  postgres:
    image: postgres:15-alpine
    container_name: user-service-postgres
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    ports:
      - '5437:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: user-service-redis
    ports:
      - '6382:6379'
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes

  user-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: user_service_app
    ports:
      - '3000:3000'

    environment:
      NODE_ENV: ${NODE_ENV}
      PORT: ${PORT}
      API_PREFIX: ${API_PREFIX}

      # Database
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_PORT: 5432
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_NAME: ${DATABASE_NAME}

      # Redis
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: 6379
      REDIS_PASSWORD:
      REDIS_TTL: ${REDIS_TTL}

      # JWT
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRATION: ${JWT_EXPIRATION}

      # Service
      SERVICE_NAME: user-service

      # Logging
      LOG_LEVEL: info

    depends_on:
      - postgres
      - redis
volumes:
  postgres_data:
  redis_data:
